sequin:
  image:
    repository: sequin/sequin
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 7376
    nodePort: 31376
  config:
    pgHostname: "{{ .Release.Name }}-postgresql"
    pgDatabase: sequin
    pgPort: 5432
    pgUsername: postgres
    pgPassword: postgres
    pgPoolSize: 20
    secretKeyBase: "wDPLYus0pvD6qJhKJICO4dauYPXfO/Yl782Zjtpew5qRBDp7CZvbWtQmY0eB13If"
    vaultKey: "2Sig69bIpuSm2kv0VQfDekET2qy8qUZGI8v3/h3ASiY="
    redisUrl: "redis://{{ .Release.Name }}-redis-master:6379"

postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: sequin
  primary:
    service:
      ports:
        postgresql: 5432

redis:
  enabled: true
  auth:
    enabled: false
  master:
    service:
      ports:
        redis: 6379
