apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sequin
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sequin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sequin
    spec:
      containers:
        - name: sequin
          image: "{{ .Values.sequin.image.repository }}:{{ .Values.sequin.image.tag }}"
          imagePullPolicy: {{ .Values.sequin.image.pullPolicy }}
          ports:
            - containerPort: 7376
          env:
            - name: PG_HOSTNAME
              value: {{ if not .Values.postgresql.enabled }}{{ .Values.externalPostgresql.host | quote }}{{ else }}{{ .Values.sequin.config.pgHostname | quote }}{{ end }}
            - name: PG_DATABASE
              value: {{ if not .Values.postgresql.enabled }}{{ .Values.externalPostgresql.database | quote }}{{ else }}{{ .Values.sequin.config.pgDatabase | quote }}{{ end }}
            - name: PG_PORT
              value: {{ if not .Values.postgresql.enabled }}{{ .Values.externalPostgresql.port | quote }}{{ else }}{{ .Values.sequin.config.pgPort | quote }}{{ end }}
            - name: PG_USERNAME
              value: {{ if not .Values.postgresql.enabled }}{{ .Values.externalPostgresql.username | quote }}{{ else }}{{ .Values.sequin.config.pgUsername | quote }}{{ end }}
            - name: PG_PASSWORD
              value: {{ if not .Values.postgresql.enabled }}{{ .Values.externalPostgresql.password | quote }}{{ else }}{{ .Values.sequin.config.pgPassword | quote }}{{ end }}
            - name: PG_POOL_SIZE
              value: {{ if not .Values.postgresql.enabled }}{{ .Values.externalPostgresql.poolSize | quote }}{{ else }}{{ .Values.sequin.config.pgPoolSize | quote }}{{ end }}
            - name: SECRET_KEY_BASE
              value: {{ .Values.sequin.config.secretKeyBase | quote }}
            - name: VAULT_KEY
              value: {{ .Values.sequin.config.vaultKey | quote }}
            - name: REDIS_URL
              value: {{ if not .Values.redis.enabled }}{{ printf "redis://%s:%s/%s" .Values.externalRedis.host (toString .Values.externalRedis.port) (toString .Values.externalRedis.database) | quote }}{{ else }}{{ .Values.sequin.config.redisUrl | quote }}{{ end }}
