apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sequin
spec:
  type: {{ .Values.sequin.service.type }}
  ports:
    - port: {{ .Values.sequin.service.port }}
      targetPort: 7376
      nodePort: {{ .Values.sequin.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-sequin
